// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjxrhzrpariazxrclbfm.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqeHJoenJwYXJpYXp4cmNsYmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTE3NTUsImV4cCI6MjA2MDM4Nzc1NX0.jlgChFy0FdkT3TwuTFiaYQlBcwCpUXzvt7QDVm2_vhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_ANON_KEY,
    {
      auth: {
        persistSession: true,
        detectSessionInUrl: true,
      },
    }
  )

